### ISSUE TITLE
Unable to generate CAPTCHA

### ISSUE THREAD

**Issue by faizal108** [APIMaker-dev/api_maker_docker_image#1]
I successfully run the docker and when i go on home page: http://127.0.0.1:4626/

![image](https://github.com/user-attachments/assets/7a90ea93-1afa-47a2-b5ae-64832a1e3f75)

when i run this command for logs : docker logs --follow api_maker_be_fe

it shows this : 

🔑 ENV Path : /root/api_maker/local.env
Swap size of system is not enough. Please increase swap using below commands
—————————————————————————— Create swap ————————————————————————
cd /var
touch swap.img
chmod 600 swap.img
dd if=/dev/zero of=/var/swap.img bs=1024k count=4000
    # 4000MiB swap size
mkswap /var/swap.img
swapon /var/swap.img
echo "/var/swap.img none swap sw 0 0" >> /etc/fstab
    # Enable your swap file during boot
——————————————————————————————————————————————————————————————
Swap size found is '1024', and it should be minimum '2000' mebibytes.
Worker exit : 1
CPU Count read from .env file.
Final CPU count for cluster  1
Worker Started : 1

**Comment by mayur-dit** [comment]
It is fixed and it should work now.
Latest image is also pushed with "latest" and "1.9.0" tag.

**Comment by its-hannan** [comment]
![Image](https://github.com/user-attachments/assets/85a0e9b4-3c5a-4f70-9308-9cbf13c1700d)

By using your guide to install latest API maker to resolve the captcha problem but it still there until it not resolved in latest API maker so is there any guidance to solve this plz tell us

**Comment by mayur-dit** [comment]
<img width="946" alt="Image" src="https://github.com/user-attachments/assets/6b56a664-5b7e-4623-9c95-9c5f1c124a8a" />

Please make sure these ports are free. You can use below package to kill processes running on those processes.
-- Try after that, it will work.
<img width="926" alt="Image" src="https://github.com/user-attachments/assets/282c5493-b449-4e34-9060-38965021e65a" />


-- Captcha is not loading means backend is not running properly. you can check logs by running below command.
`docker logs --follow api_maker_be_fe # See internal logs`
